### ISSUE TITLE
[BUG]Get stuck and sliding automatically

### ISSUE THREAD

**Issue by xingtongli** [Monomancer/SempiternalAeon#56]
When the role jump to the hanging land, if the role does not jump on the land and hit the edge of the land, the role will stuck in the air at the edge of the land.  I should release the control button to let it drop off.
When the role stand on the slope, the role will sliding down slowly.

**Comment by Jooostan** [comment]
Thank you for bringing this to our attention

**Comment by Cabbler25** [comment]
This was closed as it was already posted #46 thanks tho!
