### ISSUE TITLE
[Critical Bug] INFECTED ZIP FILE! 

### ISSUE THREAD

**Issue by RedwanIbneSerajKhan** [Monomancer/SempiternalAeon#64]
# Description

The file that you provided is infected.

# Picture of the problem

![sempiternal aeon critical bug](https://user-images.githubusercontent.com/28854577/38826241-36cf1f64-417d-11e8-8a35-5f3830362a2d.jpg)

**Comment by Jooostan** [comment]
We are looking into this. Thank you
