### ISSUE TITLE
Bat's trigger cave hitbox.

### ISSUE THREAD

**Issue by JustinHenderson98** [Monomancer/SempiternalAeon#70]
Bat's trigger the cave hitbox, and may explain why the player will randomly be sent back to the main menu. To replicate this:
i. Lure a bat to either the entrance or exit of a level. 
ii. Push the bat into the dark area.

Expected result: Player will be sent to main menu when player touches the black area.
Actual result: Player is sent back to main menu when bat touches the black area.

**Comment by Jooostan** [comment]
Thanks for bringing this to our attention
